create table tb_endereco (numero integer, id bigint generated by default as identity, cep varchar(255), cidade varchar(255), estado varchar(255), logradouro varchar(255), primary key (id));
create table tb_user (data_de_nascimento timestamp(6), endereco_principal bigint, id bigint generated by default as identity, name varchar(255), primary key (id));
create table tb_usuario_endereco (endereco_id bigint not null, usuario_id bigint not null, primary key (endereco_id, usuario_id));
alter table if exists tb_usuario_endereco add constraint FKaue719hqmvyjtgmtwpc034fvt foreign key (endereco_id) references tb_endereco;
alter table if exists tb_usuario_endereco add constraint FK9kd7o83d4v94vdsnvkymlywpl foreign key (usuario_id) references tb_user;
INSERT INTO tb_endereco (logradouro, cep, numero, cidade, estado) VALUES ('Rua do Imperador', '58288-000', '88', 'João Pessoa', 'Paraíba');
INSERT INTO tb_user (name, data_de_nascimento, endereco_principal) VALUES ('Ricardo', '1982-11-4', 1);
INSERT INTO tb_usuario_endereco (endereco_id, usuario_id) VALUES (1, 1);
